services:
  backend:
    build: Backend/.
    ports:
      - "8080:8080"
    container_name: back
  frontend:
      build: Frontend/.
      ports:
        - "9090:9090"
      container_name: front

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: a2JFEEL6hGww0dcI
    #  MONGO_INITDB_DATABASE: TACS_DB
    ports:
      - "27017:27017"
    volumes:
      - ./docker-config/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#      - mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand('ping').ok == 1" ]
      interval: 10s
      timeout: 10s
      retries: 3

  mongo-express:
      image: mongodb/mongodb-atlas-local
      container_name: mongo-express
      environment:
        ME_CONFIG_MONGODB_URL: "mongodb://root:a2JFEEL6hGww0dcI@mongodb:27017/TACS_DB"
        ME_CONFIG_BASICAUTH: "false"
      ports:
        - "8081:8081"
      depends_on:
        - mongodb
      healthcheck:
        test: [ "CMD", "curl", "--silent", "--fail", "http://localhost:8081" ]
        interval: 10s
        timeout: 10s
        retries: 3

#  volumes:
#    mongo_data:
#      driver: local

#  mongodb:
#    hostname: mongodb
#    image: mongodb/mongodb-atlas-local
#    environment:
#      - MONGODB_INITDB_ROOT_USERNAME=jpolito
#      - MONGODB_INITDB_ROOT_PASSWORD=ca6RYKD535v6ruHM
#    ports:
#      - 27018:27017
#    volumes:
#      - data:/data/db
#      - config:/data/configdb
