version: '3.8'
services:
  backend:
    build: Backend/.
    ports:
      - "8080:8080"
    container_name: back
    environment:
      - aws.s3.bucket=${AWS_S3_BUCKET}
      - aws.access-key-id=${AWS_ACCESS_KEY_ID}
      - aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}
      - aws.s3.region=${AWS_S3_REGION}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb

  frontend:
    build: Frontend/.
    ports:
      - "9090:9090"
    container_name: front

  mongodb:
    image: mongo:8.0
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: "root"
#      MONGO_INITDB_ROOT_PASSWORD: "pass"
#      MONGO_INITDB_DATABASE: "TACS_DB"
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./docker-config/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_data:/data/db      # uncomment if you want persistent DB
#    healthcheck:
#      test: [ "CMD", "mongo", "--eval", "db.runCommand('ping').ok == 1" ]
#      interval: 10s
#      timeout: 10s
#      retries: 3

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
#      ME_CONFIG_MONGODB_SERVER: mongodb    # name of your mongo service!
#      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017
#      ME_CONFIG_MONGODB_URL: "mongodb://root:pass@mongodb:27017/admin"
#      ME_CONFIG_BASICAUTH: "false"         # disables login for mongo-express UI
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "admin123"
#      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
#      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
#      ME_CONFIG_MONGODB_ADMINPASSWORD: "pass"

    ports:
      - "8081:8081"
    depends_on:
      - mongodb
#    healthcheck:
#      test: [ "CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8081 || exit 1" ]
#      interval: 10s
#      timeout: 10s
#      retries: 3

# (Opcional) Volumen persistente
volumes:
  mongo_data: