spring.application.name=cartasIntercambio
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss 
spring.jackson.serialization.write-dates-as-timestamps=false
server.address=0.0.0.0
server.port=8080

spring.data.mongodb.host=mongodb
spring.data.mongodb.port=27017
spring.data.mongodb.database=cartas_intercambio
# Por si lo necesitás
spring.data.mongodb.auto-index-creation=true